### PR TITLE
Add GitHub Actions workflow for automated testing

### PR DESCRIPTION
**Pull request by mirzaim**
This PR introduces a GitHub Actions workflow for automated testing, addressing part of Issue #32. The workflow is configured to run unit tests on pushes and pull requests to specified branches.

### CODE REVIEW

**Comment by mirzaim** [comment]
I tested the workflow on my [own fork](https://github.com/mirzaim/Gestalt/pull/1), and it functions as expected.

**Comment by HLRichardson-Git** [comment]
Out of curiosity, what are the includes for `cstring` and `climits` for?

Is there a way to run the actions on your fork to watch that the unit tests pass? I see a blue check mark next to the action, but I thought the check mark was suppose to be green when the action is "passing".

**Comment by mirzaim** [comment]
On my local machine, the compilation worked fine without explicitly including headers like `cstring`, even though we used functions like `memcpy` and constants from `climits`. However, GitHub Actions flagged errors, such as "memcpy is undefined," which you can see [in this example run](https://github.com/mirzaim/Gestalt/actions/runs/11645079295/job/32427703226). Adding these headers resolved the issue in the CI environment.

As for the Actions status, it’s green on my fork, as shown here:
image

**Comment by HLRichardson-Git** [comment]
Thanks for this mirzaim! This was an issue that I was gonna keep on delaying, so I appreciate you picking it up. This is a big improvement to Gestalt!

Sorry for the delay, I had to leave for a bit. I also wanted to do a bit more research into how the GitHub actions worked to make sure I understood it.

**Pull request merged**
